services:
  blueprint-db:
    image: mysql:latest
    env_file: .env
    container_name: ${CONTAINER_NAME}-db
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_NAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin-blueprint:
    image: phpmyadmin/phpmyadmin:latest
    env_file: .env
    container_name: ${CONTAINER_NAME}-phpmyadmin
    environment:
      PMA_HOST: blueprint-db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - blueprint-db
    networks:
      - app-network
  
  blueprint:
    build: ./
    env_file: .env
    container_name: ${CONTAINER_NAME}-site
    ports:
      - "3000:3000"
    environment:
      DB_HOST: blueprint-db
      DB_USER: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    depends_on:
      - blueprint-db
      - phpmyadmin-blueprint
    networks:
      - app-network

networks:
  app-network:
