services:
  database:
    image: mysql:latest
    env_file: .env
    container_name: ${CONTAINER_NAME}-db
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./blueprint/lib/db_data:/var/lib/mysql
      - ./dbstart:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - app-network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    env_file: .env
    container_name: ${CONTAINER_NAME}-phpmyadmin
    environment:
      PMA_HOSTS: database,wordpress-db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - database
    ports:
      - "8080:80"
    networks:
      - app-network
  
  web-app:
    build: ./blueprint
    env_file: .env
    container_name: ${CONTAINER_NAME}-site
    environment:
      DB_HOST: database
      DB_NAME: ${DATABASE_NAME}
      DB_USER: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3000:3000"
    volumes:
      - ./blueprint:/blueprint
      - /blueprint/node_modules
    depends_on:
      - database
      - phpmyadmin
    networks:
      - app-network

  wordpress-db:
    image: mysql:latest
    env_file: .env
    container_name: ${CONTAINER_NAME}-wordpress-db
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DATABASE_NAME}
      MYSQL_USER: ${WORDPRESS_DATABASE_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DATABASE_PASSWORD}
    ports:
      - "3307:3306"
    networks:
      - app-network

  wordpress:
    image: wordpress:latest
    env_file: .env
    container_name: ${CONTAINER_NAME}-wordpress
    environment:
      WORDPRESS_DB_HOST: ${CONTAINER_NAME}-wordpress-db
      WORDPRESS_DB_USER: ${WORDPRESS_DATABASE_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DATABASE_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DATABASE_NAME}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_ALLOW_MULTISITE', true);
    depends_on: 
      - wordpress-db
    ports:
      - "8000:80"
    volumes:
      - ./Wordpress:/var/www/html
    networks:
      - app-network
    
  wordpress-cli:
    image: wordpress:cli
    env_file: .env
    container_name: ${CONTAINER_NAME}-wordpress-cli
    environment:
      WORDPRESS_DB_HOST: ${CONTAINER_NAME}-wordpress-db
      WORDPRESS_DB_USER: ${WORDPRESS_DATABASE_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DATABASE_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DATABASE_NAME}
    user: '33'
    depends_on:
      - wordpress-db
      - wordpress
    volumes:
      - ./Wordpress:/var/www/html
      - ./blueprint/lib/wordpress_setup:/temp
    command: >
      /bin/sh -c '
      sleep 60;
      wp core multisite-install --path='/var/www/html' --url=localhost:8000 --title="blueprint" --admin_user=${WORDPRESS_DATABASE_USER} --admin_password=${WORDPRESS_DATABASE_PASSWORD} --admin_email=foo@bar.com;
      wp plugin install jwt-authentication-for-wp-rest-api --activate
      cp /temp/.htaccess_dummy /var/www/html/.htaccess;
      chmod 644 /var/www/html/.htaccess;
      echo "SETUP DONE!";
      '
    networks:
     - app-network
networks:
  app-network:
      
      